package server.dto;

import stream.BufferReader;
import stream.BufferWriter;
import stream.Reader;
import stream.Writer;

import java.nio.channels.SocketChannel;

public class Conn {
    private static final int BUFFER_SIZE = 64 * 1024; // 64KB initial buffer size

    private final SocketChannel channel;
    private boolean wantRead = false;
    private boolean wantWrite = false;
    private boolean wantClose = false;
    private final Writer writer;
    private final Reader reader;
    private final ConnectionType connectionType;

    public Conn(SocketChannel channel, ConnectionType connectionType) {
        this.channel = channel;
        this.wantRead = true;
        Buffer incoming = new Buffer(BUFFER_SIZE);  // data to be parsed by application
        Buffer outgoing = new Buffer(BUFFER_SIZE); // responses generated by application
        this.writer = new BufferWriter(channel, outgoing);
        this.reader = new BufferReader(channel, incoming);
        this.connectionType = connectionType;
    }

    public void wantRead() {
        this.wantRead = true;
        this.wantWrite = false;
    }

    public void wantWrite() {
        this.wantWrite = true;
        this.wantRead = false;
    }

    public void wantClose() {
        this.wantClose = true;
    }


    public SocketChannel getChannel() {
        return channel;
    }

    public boolean isWantRead() {
        return wantRead;
    }

    public boolean isWantWrite() {
        return wantWrite;
    }

    public boolean isWantClose() {
        return wantClose;
    }

    public Writer getWriter() {
        return writer;
    }

    public Reader getReader() {
        return reader;
    }

    public ConnectionType getConnectionType() {
        return connectionType;
    }

    public enum ConnectionType {
        CLIENT_CONNECT,
        REPLICA_CONNECT,
    }
}
