package server.nonblocking;

import lombok.Getter;
import lombok.Setter;

import java.nio.channels.SocketChannel;

@Getter
class Conn {
    private static final int BUFFER_SIZE = 64 * 1024; // 64KB initial buffer size

    private SocketChannel channel;
    @Setter
    private boolean wantRead = false;
    @Setter
    private boolean wantWrite = false;
    @Setter
    private boolean wantClose = false;
    private Buffer incoming;  // data to be parsed by application
    private Buffer outgoing;  // responses generated by application

    Conn(SocketChannel channel) {
        this.channel = channel;
        this.wantRead = true;
        this.incoming = new Buffer(BUFFER_SIZE);
        this.outgoing = new Buffer(BUFFER_SIZE);
    }
}
