package server.nonblocking;

import lombok.Getter;
import stream.BufferReader;
import stream.BufferWriter;
import stream.Reader;
import stream.Writer;

import java.nio.channels.SocketChannel;

@Getter
class Conn {
    private static final int BUFFER_SIZE = 64 * 1024; // 64KB initial buffer size

    private final SocketChannel channel;
    private boolean wantRead = false;
    private boolean wantWrite = false;
    private boolean wantClose = false;
    private final Writer writer;
    private final Reader reader;

    Conn(SocketChannel channel) {
        this.channel = channel;
        this.wantRead = true;
//        this.incoming = new Buffer(BUFFER_SIZE);
        Buffer incoming = new Buffer(BUFFER_SIZE);  // data to be parsed by application
        // responses generated by application
        Buffer outgoing = new Buffer(BUFFER_SIZE);
        this.writer = new BufferWriter(channel, outgoing);
        this.reader = new BufferReader(channel, incoming);
    }

    public void wantRead() {
        this.wantRead = true;
        this.wantWrite = false;
    }

    public void wantWrite() {
        this.wantWrite = true;
        this.wantRead = false;
    }

    public void wantClose() {
        this.wantClose = true;
    }
}
